---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage
  labels:
    type: nfs
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "{{ NFS_INTERNAL_IP }}"
    path: "{{ NFS_EXPORT_FILE_PATH }}"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storage-nfs
  resources:
    requests:
      storage: 5Gi
  selector: 
    matchLabels:
      type: nfs


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: myregistry.azurecr.io/samples/nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs-storage
          mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-nginx
